neuro_san/http_sidecar/handlers/base_request_handler.py
neuro_san/http_sidecar/http_sidecar.py
neuro_san/http_sidecar/logging/http_logger.py

This PR makes sure that for any http logger call, our logger filter sets up logging record at least with some default value ("None") for every key from forwarded request meta-data.
The problem shows up actually when we use Http logger outside of request handling context,
but this case is now fixed too.

UN-3077 Fix the problem with setting default field values for Http server logging.

---

neuro_san/internals/chat/chat_history_message_processor.py
neuro_san/internals/chat/data_driven_chat_session.py

Requested by 1C guys.
Allow a "max_message_history" on the front man agent spec to potentially limit the number of messages sent back in the chat history. Preserved context favors the N most recent messages.
This becomes a somewhat simple/reasonable way to deal with input context limits for long conversations like 1C has without getting into the nitty-gritty of token counting and input context limits when agents can now have fallback llms of varying capabilities.  Some of the 1C responses get pretty long and the number of interactions can be pretty high as well.
Tested: music_nerd_pro with and without a max_message_history of 2.
Q: Who did Yellow Submarine?
A: Beatles
Q: Where were they from?
A: Liverpool
Q: What album was it on?
A: Revolver     <- No max_message_history
A: What are you …

UN-3075 max_message_history

---

neuro_san/internals/run_context/langchain/default_llm_info.hocon

- Fix typo in default_llm_info.hocon.
- Run agent hocon with claude-3-opus model.

UN-3084-neuro-san-typo-for-claude-3-opus-model-in-default-llm-info-hoconFix typo in default_llm_info.hocon

---

neuro_san/http_sidecar/handlers/base_request_handler.py
neuro_san/http_sidecar/handlers/concierge_handler.py
neuro_san/http_sidecar/handlers/connectivity_handler.py
neuro_san/http_sidecar/handlers/function_handler.py
neuro_san/http_sidecar/handlers/openapi_publish_handler.py
neuro_san/http_sidecar/handlers/streaming_chat_handler.py
neuro_san/http_sidecar/http_sidecar.py
neuro_san/http_sidecar/interfaces/agent_authorizer.py

This PR switches Http server for agents requests to dynamic routing.
That means that our separate policy (very straightforward for now)
will decide which agent names are recognized as valid to pass API requests through.
Tested by running the usual "chicken", "music_nerd" and "hello_world" tests with all agents enabled,
and then trying "hello_world" test with internal debug thread flipping enable/disable flag for this agent repeatedly
without restarting the server.

UN-2778 Dynamic routing of Http requests to agents.

---

tests/framework/driver/assert_capture.py
tests/framework/driver/data_driven_agent_test_driver.py
tests/framework/evaluators/gist_agent_evaluator.py

Tests can now specify a top level "success_ratio".  This is of the form "A/B" where B iterations are performed and at least A iterations need to pass in order to be successful. By default this ratio is "1/1".
Eventually this ratio can be used in a development scenario where B iterations are performed and we collect and analyze the reasons why the test failed however many times it did. That is for a later PR, but on its own this allows for the imperfections inherent in LLM-based agents to not necessarily fail when they are Good Enough for testing purposes.

UN-3115 success_ratio in data-driven agent tests

---

.github/workflows/integration.yml

This PR puts in the necessary scheduling directive to allow us to manually trigger the integration test when needed.

Enable manual triggering for integration test

---

neuro_san/http_sidecar/handlers/base_request_handler.py
neuro_san/http_sidecar/handlers/concierge_handler.py
neuro_san/http_sidecar/handlers/connectivity_handler.py
neuro_san/http_sidecar/handlers/function_handler.py
neuro_san/http_sidecar/handlers/streaming_chat_handler.py

The previous handlers didn't seem to do the trick. ChatGPT 🙇🏻 suggests this.
TBD: is non-async okay?

UN-3080 Another attempt at getting OPTIONS handlers correct

---

neuro_san/http_sidecar/handlers/base_request_handler.py
neuro_san/http_sidecar/handlers/connectivity_handler.py
neuro_san/http_sidecar/handlers/function_handler.py
neuro_san/http_sidecar/handlers/streaming_chat_handler.py
neuro_san/http_sidecar/http_sidecar.py
neuro_san/http_sidecar/interfaces/agents_updater.py
neuro_san/internals/interfaces/agent_state_listener.py
neuro_san/internals/tool_factories/service_tool_factory_provider.py
neuro_san/service/agent_server.py
neuro_san/service/agent_servicer_to_server.py
neuro_san/service/dynamic_agent_router.py
neuro_san/session/direct_concierge_session.py

This PR implements dynamic collection of agents supported by running neuro-san server.
Overall architecture looks like this:
- singleton instance of ServiceToolFactoryProvider keeps a dynamic table of agent names mapped to their AgentToolFactory instances. This is our "source of truth" representing actual state of the service;
- ServiceToolFactoryProvider provides methods to add and remove agent+AgentToolFactory pairs to/from the state;
- singleton instance of DynamicAgentRouter works as universal gRPC requests handler for any agent+method pair we may throw at the server. Again, it keeps an internal dynamic table of agent names which are allowed for serving requests;
- there are state listeners which can be registered with ServiceToolFactoryProvider to be notified about state changes, and …

UN-2778 Dynamic agent endpoints

---

README.md
neuro_san/client/agent_cli.py
neuro_san/deploy/Dockerfile
neuro_san/registries/assess_failure.hocon
neuro_san/registries/gist.hocon
neuro_san/registries/hello_world.hocon
neuro_san/registries/manifest.hocon
neuro_san/test/assessor/assessor.py
neuro_san/test/assessor/assessor_assert_forwarder.py
neuro_san/test/driver/assert_capture.py
neuro_san/test/driver/data_driven_agent_test_driver.py
neuro_san/test/evaluators/gist_agent_evaluator.py
neuro_san/test/interfaces/assert_forwarder.py
neuro_san/test/unittest/unit_test_assert_forwarder.py
tests/fixtures/hello_world/hello_world.hocon

* First attempt at an agent failure Assessor that, with the aid of a hocon test case, can report failure classifications on repeated test attempts that use the "gist" evaluator.
* Some adding to AssertForwarder and pals to make certain failures more specific.
* Create a test case for hello_world and use it to begin to repair the prompts there. Still not perfect, but actually passes much more often than before.
* Update README with more reliable hello_world findings.
Some other random fixes:
* Remove "service" as a connection option from agent_cli.py.  Let's be specific, people.
* Tweak to Dockerfile to reference python logging cookbook.
* Remove redundancy in README
Sample output of the Assessor:
```
$ python -m neuro_san.test.assessor.assessor --test_hocon …
```

UN-3116 First stab at agent failure assessor

---

docs/test_case_hocon_reference.md
tests/fixtures/music_nerd_pro/beatles_prompt.txt

Document the hocon that describes the data-driven test cases under tests/fixtures.
@vince-leaf is the primary reviewer.
@kxk302 might take special interest if he is going to use the test infrastructure to help him with his fine-tuning training.

Test case hocon reference doc

---

neuro_san/http_sidecar/handlers/streaming_chat_handler.py

This PR is a pretty much speculative attempt to help with an issue reported by 1C group - 
some streaming chat requests not reaching neuro-san http server.
Idea (GPT suggested) that we may face a situation when long-running requests
lead to "keep-alive" server connections to be closed by a server, whereas client still trying to reuse them.
Change itself doesn't seem to affect client-initiated chats with neuro-san,
but timeout issue itself I hasn't been able to reproduce.

UN-3144 Potential help with timeout for long-lived chat connections.

---

neuro_san/registries/assess_failure.hocon
neuro_san/registries/date_time.hocon
neuro_san/registries/esp_decision_assistant.hocon
neuro_san/registries/gist.hocon
neuro_san/registries/hello_world.hocon
neuro_san/registries/intranet_agents.hocon
neuro_san/registries/manifest.hocon
neuro_san/registries/math_guy.hocon
neuro_san/registries/math_guy_passthrough.hocon
neuro_san/registries/music_nerd.hocon
neuro_san/registries/music_nerd_pro.hocon
neuro_san/registries/prebuilt_search_tool.hocon
neuro_san/registries/website_rag.hocon
neuro_san/registries/website_search.hocon
neuro_san/registries/website_search_usage_example.hocon
tests/fixtures/esp_decision_assistant/fallbacks_and_commondef_values.hocon
tests/fixtures/hello_world/hello_world.hocon
tests/fixtures/math_guy/basic_sly_data.hocon
tests/fixtures/math_guy/forwarded_sly_data.hocon
tests/fixtures/music_nerd/beatles_with_history.hocon

Like the title says, add links (in comments) to:
* manifest.hocon to manifest_hocon_reference.md
* agent.hocon files to agent_hocon_reference.md
* test case.hocon files to test_case_hocon_reference.md
the default_llm_info.hocon already as a link to its reference docs.
Folks should consider similar links for neuro-san-demos.

Add links in hocon files to reference documentation

---

neuro_san/http_sidecar/handlers/base_request_handler.py
neuro_san/http_sidecar/handlers/concierge_handler.py
neuro_san/http_sidecar/handlers/connectivity_handler.py
neuro_san/http_sidecar/handlers/function_handler.py
neuro_san/http_sidecar/handlers/health_check_handler.py
neuro_san/http_sidecar/handlers/openapi_publish_handler.py
neuro_san/http_sidecar/handlers/streaming_chat_handler.py
neuro_san/session/http_service_agent_session.py

This PR implements several fixes to neuro-san Tornado request handlers.
- Make sure that handler.finish() is always called directly, not awaited, as recommended by Tornado docs;
- We add logging for possible tornado.iostream.StreamClosedError exception;
- Connections are back to being keep-alive by default, since this doesn't seem to be the source of issues we observe.
Tested by running local mini stress test:
3 clients each running 30x3 chat requests - around 1000 chat results in total. Server survives.

Fixes for tornado handlers.

---

neuro_san/registries/music_nerd_pro.hocon
neuro_san/registries/website_search.hocon

Remove `command` from the coded tools in `music_nerd_pro.hocon` and `website_search.hocon`

UN-3131 remove command key from coded tool nodes in neuro-san

---

neuro_san/service/registries_watcher/periodic_updater/manifest_periodic_updater.py
neuro_san/service/registries_watcher/periodic_updater/registry_event_observer.py
neuro_san/service/registries_watcher/periodic_updater/registry_polling_observer.py
requirements.txt

This PR implements another version of agents registry updater - the one that goes for direct polling of target registry directory instead of relying on OS-level file system events.
OS-level events work just fine for truly local setup,
but have problems if we deal with mapped storage volumes, especially if file system of different kinds are mixed.
Polling is much more reliable, but relatively CPU-intensive.
Tested: running neuro-san server in a Docker container, with registry mapped to host-side directory.
Changes in this directory are detected by the server with proper reaction.
Also: running medium stability test with another script periodically updating agents registry.

UN-3155 Polling agents registry updater.

---

neuro_san/http_sidecar/handlers/health_check_handler.py

Previously there was no CORS support for the root (healthcheck). This is useful (for example) for the UI project to "test on connect" when the user enters a URL, so we can hit the healthcheck URL from the browser.

UN-3166 Add CORS support for healthcheck URL "/"

---

docs/agent_hocon_reference.md
neuro_san/api/grpc/agent.proto
neuro_san/api/grpc/agent_pb2.py
neuro_san/api/grpc/agent_service.json
neuro_san/registries/math_guy.hocon

Idea from a conversation with Paul, this ended up being a lot easier than I thought it would be.
Allowing for sly_data_schema to be sent in the Function() response means that a generic client like
MAAUI can prompt for user-specific information in a generic way.  This should increase the utility of what other
people can demo for us in that for specific cases we don't have to provide deploy-time environment variables 
for special accounts.
Worth noting that there is no checking for the required fields of the schema on the server side.

UN-3171 Add sly_data_schema to FunctionResponse

---

neuro_san/http_sidecar/handlers/base_request_handler.py
neuro_san/http_sidecar/handlers/concierge_handler.py
neuro_san/http_sidecar/handlers/connectivity_handler.py
neuro_san/http_sidecar/handlers/function_handler.py
neuro_san/http_sidecar/handlers/streaming_chat_handler.py
neuro_san/http_sidecar/http_sidecar.py
neuro_san/http_sidecar/interfaces/agents_updater.py
neuro_san/service/agent_main_loop.py
neuro_san/service/agent_server.py

This PR moves Tornado http server from separate process to separate thread in main neuro-san process.
The move will allow http service stack to access neuro-san internals directly, without relying on local gRPC endpoint.
Note that switch away from local gRPC is not done in this PR - except for Concierge service query.
Switching chat request to using AsyncAgentService is somewhat tricky and warrants I think a separate PR.
As for simple Function and Connectivity requests - right now it's not worth it to mix/match direct and gRPC sessions.
Tested: stability test running concurrent local clients:
2 grpc + 2 http each doing 20x3 one-shot chats.

UN-3137 Switch to Tornado http server in-process as a separate thread.

---

neuro_san/http_sidecar/handlers/health_check_handler.py
neuro_san/http_sidecar/http_sidecar.py

This PR fixes health check request handler.
Since we are defining our custom "default" Tornado request logger,
several things have to be added to any request handler,
namely self.logger and self.get_metadata() method.

Fix health check request handler.

---

neuro_san/http_sidecar/handlers/base_request_handler.py
neuro_san/http_sidecar/handlers/connectivity_handler.py
neuro_san/http_sidecar/handlers/function_handler.py
neuro_san/http_sidecar/handlers/streaming_chat_handler.py
neuro_san/http_sidecar/http_sidecar.py
neuro_san/http_sidecar/interfaces/agent_authorizer.py
neuro_san/internals/messages/chat_message_type.py

This PR finally switches from gRPC sessions to asynchronous agent service for executing neuro-san requests.
AsyncAgentService has been added to codebase in previous PR.
Tested: by stability test.

Un-3137 Use AsyncAgentService for http service stack.

---

build_scripts/run_pylint.sh
neuro_san/interfaces/agent_session.py
neuro_san/interfaces/agent_session_constants.py
neuro_san/interfaces/async_agent_session.py
neuro_san/session/abstract_http_service_agent_session.py
neuro_san/session/async_grpc_service_agent_session.py
neuro_san/session/async_http_service_agent_session.py
neuro_san/session/external_agent_session_factory.py
neuro_san/session/grpc_service_agent_session.py
neuro_san/session/http_service_agent_session.py
requirements.txt

Some refactoring, some new capability:
* Move common constants to new AgentSessionConstants interface
* Remove use of DEFAULT_AGENT_NAME constant.  Throw an exception if agent_name is not set in sessions now.
* Create an AsyncHttpServiceAgentSession class.  This is based on aiohttp which seems most similar to requests lib.
* Consolidate common code of sync and asynchronous versions into AbstractHttpServiceAgentSession
* Move default communication for external agents to use the new AsyncHttpServiceAgentSession class as opposed to its gRPC counterpart.
Tested: math_guy_passthrough on http and grpc via agent_cli.
@andreidenissov-cog is primary

UN-3071 Switch to using HTTP for external agents from gRPC

---

neuro_san/internals/chat/data_driven_chat_session.py
neuro_san/internals/graph/activations/calling_activation.py
neuro_san/internals/graph/activations/front_man_activation.py
neuro_san/internals/graph/registry/activation_factory.py
neuro_san/internals/graph/registry/agent_tool_registry.py
neuro_san/internals/interfaces/agent_registry.py
neuro_san/internals/interfaces/front_man.py
neuro_san/session/async_direct_agent_session.py
neuro_san/session/direct_agent_session.py

* Use the inspector aspect for function() instead of having to fully create a FrontMan instance. Cleaner.
* Break out an interface for FrontMan that DataDrivenChat uses.
* Old FrontMan class renamed to FrontManActivation like its brethren.

UN-3192 More graph-level interface refactors

---

neuro_san/service/agent_service.py
neuro_san/service/async_agent_service.py
neuro_san/service/chat_message_converter.py

This PR converts all ChatMessageType enum values in outgoing chat responses to strings
as expected by UI clients.
Will work also for agent_cli client, though it can already handle ChatMessageType int values if they do come from a server.
Tested by observing chat response messages being sent to output
with ChatMessageType values represented as strings.

UN-3017 Convert outgoing chat messages to expected format.

---

neuro_san/http_sidecar/http_sidecar.py

This PR fixes logic flaw in handling http server start-up.
We were relying on a fixed though rather generous timeout for http server
while waiting for gRPC server to do its initialization business and signal http to go ahead.
For some reason, on Ubuntu I see gRPC server taking much more time than could be expected,
so timeout fails.
Instead, now we'll be waiting for startup signal basically indefinitely,
with logging spam to get the message across that http server is failing to start.

UN-3227 Fix timeout handling for http server start-up.

---

neuro_san/http_sidecar/handlers/base_request_handler.py

This is basically a hack to help Tornado async streaming force out output http buffers
and ensure that client will get "one response per http chunk".
That seems to work, at least until UI client knows how to handle "multiple responses per chunk",
which would be much more reliable.
In case of emergency: play with delay duration.
Tested with MAA UI against local neuro-san server:
music-nerd-pro, esp-assistant, web-search. 
No amnesia noted.
BTW: putting in time.sleep(0) doesn't seem to help.

Put in a delay to help force output buffer flush.

---

docs/test_case_hocon_reference.md
tests/fixtures/esp_decision_assistant/fallbacks_and_commondef_values.hocon

Using the assessor, I was able to deduce that the problem was in the test and not the agent.

UN-3191 Fix esp_decision_assist gist test prompt to accommodate for intermittent failures.

---

neuro_san/client/agent_cli.py
neuro_san/client/agent_session_factory.py
neuro_san/client/direct_agent_session_factory.py
neuro_san/session/async_grpc_service_agent_session.py
neuro_san/session/direct_agent_session.py
neuro_san/session/grpc_service_agent_session.py
neuro_san/test/driver/data_driven_agent_test_driver.py
requirements.txt

* Use Timeout.check_if_not_none() to avoid an error
* Pass umbrella_timeout down to DirectSession and use it.
* Use latest leaf-server-common and leaf-common
* Catch case of timeout failure w/ DirectAgentSession that @vince-leaf found and print out nice message.

UN-3235 Allow DirectAgentSession Timeout

---

neuro_san/http_sidecar/http_sidecar.py
neuro_san/internals/tool_factories/service_tool_factory_provider.py

This PR fixes a problem with dynamic manifest/agent .hocon files updates
when using http service stack.
Problem surfaced now because previously we were always going through gRPC service, which works.
Now direct http route ran into this issue.
Fix tested by: modifying hello_world.hocon file for "function" request,
enabling/disabling hello_world + music_nerd agents in manifest.hocon
and observing results from CLI client requests.
gRPC route continues to work.

UN-3237 Fix dynamic manifest updating for http service path.

---

neuro_san/client/direct_agent_session_factory.py
neuro_san/internals/run_context/langchain/core/langchain_run_context.py
neuro_san/internals/run_context/utils/external_tool_adapter.py
neuro_san/session/external_agent_session_factory.py
neuro_san/session/missing_agent_check.py

I noticed in the previous PR that a nice error message was no longer in place when there was a problem with the agent name on the user side.  Reinstate that and some similar missing external agent messaging that fell by the wayside when I switched to http from grpc.
Tested:
Agent exist vs not for direct, grpc, http
External agent exist vs not for direct, grpc, http

UN-3218 restore missing agent error in a few places

---

neuro_san/http_sidecar/handlers/health_check_handler.py

With this change the health-check would now return:
```
{
"service": "neuro-san agents",
"status": "healthy",
"versions": {
"neuro-san": "0.5.36"
}
}
```
An open question is do we want to report more than just the neuro-san version?
Can go there if there is demand.

UN-3225 Add library version(s) to health-check

---

neuro_san/session/abstract_http_service_agent_session.py
neuro_san/session/async_http_service_agent_session.py
neuro_san/session/http_service_agent_session.py

@Noravee was reporting that using http sessions for external agents was timing out and causing agent failures.
This is different behavior than what we had seen with gRPC sessions.
I was able to chase it down to the grpc bowels of hell to see that in grpc-land we had specifically been passing in a None timeout (meaning infinite) by default for streaming_chat() for the gRPC case.
This was not the case for the HTTP session. This PR should make that parity now.

UN-3253 Default infinite timeout for streaming_chat() over HTTP

---

neuro_san/internals/run_context/langchain/llms/default_llm_info.hocon

- Add key `gpt-4.1-2025-04-14` in `default_llm_info.hocon`
- Add key `gpt-4.1` which points to `gpt-4.1-2025-04-14` in `default_llm_info.hocon`
- Add key `azure-gpt-4.1` which points to `gpt-4.1-2025-04-14` in `default_llm_info.hocon`
- Run `google_serper` with `gpt-4.1-2025-04-14` and `gpt-4.1`

UN-3208 Add azure gpt-4.1 model to default_llm_info

---

requirements.txt

A dependabot warning is out for earlier versions of urllib3.
While we do use it in ExternalAgentParsing, it's only for basic parsing.
No reason we be capping the version here.

Allow newer versions of urllib3 for dependabot

---

neuro_san/client/thinking_file_message_processor.py

@babakatwork is the primary reviewer
* When we get an OSError which is a "Filename too long" error, try again to write the filename as a uuid.
* Since it's possible for filenames to now not match the agent's full origin string they belong to, we add this as a preface to any newly created file.

UN-3273 Fix 'Filename too long' by using uuids as filenames when that occurs

---

neuro_san/internals/graph/registry/agent_network.py
neuro_san/registries/assess_failure.hocon
neuro_san/registries/bing_search.hocon
neuro_san/registries/date_time.hocon
neuro_san/registries/esp_decision_assistant.hocon
neuro_san/registries/gist.hocon
neuro_san/registries/google_serper.hocon
neuro_san/registries/hello_world.hocon
neuro_san/registries/intranet_agents.hocon
neuro_san/registries/math_guy.hocon
neuro_san/registries/math_guy_passthrough.hocon
neuro_san/registries/music_nerd.hocon
neuro_san/registries/music_nerd_pro.hocon
neuro_san/registries/music_nerd_pro_llm_anthropic.hocon
neuro_san/registries/website_rag.hocon
neuro_san/registries/website_search.hocon
neuro_san/registries/website_search_usage_example.hocon

* Vet front man to be sure it does not have a class or toolbox definition
* Clearer assert if front man cannot be found
* Modify comments in hocon files to better reflect front-man criteria
* Modify comments in hocon files that do not actually apply to the situation.

UN-3277 Clearer assert on what makes a front-man / comments in hocons

---

.github/workflows/smoke.yml
tests/conftest.py

I've added the GOOGLE_API_KEY to our neuro-san repo and this PR provides the little bit of infrastructure to use that. @vince-leaf When you are ready, just add the 'gemini' mark to your new tests and it _should_ just work.

Put in support for tests marked 'gemini'

---

neuro_san/internals/filters/answer_message_filter.py
neuro_san/message_processing/basic_message_processor.py

@vince-leaf found a problem with the new structure stuff checked in earlier today where the client side was returning None for an answer for grpc only.
What is happening is:
* server infrastructure populates text as non-None empty string (len==0). (This allows direct and http to be fine)
* grpc marshaling turns an empty string into a None value over the wire
* Client side couldn't deal with None text value even though there was happy stuff in structure.

UN-3305 Fix message processing on grpc when text is None

---

neuro_san/service/http/handlers/base_request_handler.py

Update neuro-san http server to allow the 'user_id' param.
Tested this by pointing my local MAA UI with https://github.com/cognizant-ai-lab/neuro-ui/pull/66 to a local Neuro-San instance with this PR.

UN-3327 - Update neuro-san http server to allow the 'user_id' param.

---

neuro_san/service/http/handlers/base_request_handler.py
neuro_san/service/main_loop/server_main_loop.py

This PR extends setup for server requests metadata keys by using both:
--forwarded_request_metadata CLI parameter (env var AGENT_FORWARDED_REQUEST_METADATA) and
--usage_logger_metadata CLI parameter (env var AGENT_USAGE_LOGGER_METADATA).
Final metadata keys set is a union of both collections.
If CORS headers are enabled for http server,
they are specified also as those combined metadata keys.
Tested by manual debug output of final metadata keys for various combinations of env variables.

Un-3330 Set metadata keys from env variables.

---

neuro_san/service/generic/agent_service_provider.py
neuro_san/service/generic/async_agent_service_provider.py
neuro_san/service/grpc/grpc_agent_service.py
neuro_san/service/http/handlers/base_request_handler.py
neuro_san/service/http/handlers/connectivity_handler.py
neuro_san/service/http/handlers/function_handler.py
neuro_san/service/http/handlers/streaming_chat_handler.py
neuro_san/service/http/server/http_sidecar.py

Main idea of this PR is switch to "lazy" service instances instantiation.
Right now, we always create service instances - 2 of them in fact for each agent defined in server manifest;
one for gRPC, one for http, even if say we don't use gRPC for this particular server invocation,
and only use a single agent for chat.
Each service creation involves reading at least 2 files, which adds up.
Changing to service instantiation on demand makes server start up much faster.
There is an initial lag of course for loading all Python classes, but nothing to be done for that I guess.

UN-3310 Faster server startup.

---

requirements.txt

Blackduck is flagging langchain 0.3.10 as an issue. It advises 0.3.15 as the minimum fix. I updated the requirements.txt to specify 0.3.15 as the minimum for langchain.

Updated to use langchain 0.3.15 as a minimum release.

---

neuro_san/internals/interfaces/agent_state_listener.py
neuro_san/internals/interfaces/agent_storage_source.py
neuro_san/internals/network_providers/agent_network_storage.py
neuro_san/service/grpc/grpc_agent_server.py
neuro_san/service/http/server/http_server.py

This is in preparation for > 1 source of AgentStateListener messages.  For now there is only the one public source.
Tested: math_guy_passthrough with switching agent hocon definitions.

Send the source of the message to the AgentStateListener

---

neuro_san/service/grpc/grpc_agent_server.py
neuro_san/service/http/server/http_server.py
neuro_san/service/main_loop/server_main_loop.py
neuro_san/service/main_loop/server_status.py
neuro_san/service/main_loop/service_status.py
neuro_san/service/registries_watcher/periodic_updater/manifest_periodic_updater.py

This PR adds logic to separately enable or disable services we run in neuro-san server:
gRPC, http and manifest updater.
ServerStatus class is extended to use ServiceStatus instances for each service we run.
Tested: running neuro-san with different combinations of enabled services.

UN-3347 gRPC/http services separate enable/disable switch.

---

neuro_san/internals/graph/activations/calling_activation.py
neuro_san/internals/run_context/factory/run_context_factory.py

An `AttributeError` was raised when accessing `.get()` on `self.llm_config`, which was unexpectedly `None`. This happened because an empty `llm_config` in the HOCON config was being explicitly set to `None` in `calling_activation.py`, preventing the fallback logic in `run_context_factory.py` from applying the intended default configuration.
- Removed the logic in `calling_activation.py` that sets `llm_config = None` when it is an empty dictionary.
- Updated `run_context_factory.py` to defensively fallback to the default config if `"llm_config"` is `None`, using:
```python
default_llm_config = use_config.get("llm_config") or default_llm_config
```
These changes ensure that the default LLM configuration is correctly applied when `llm_config` is missing or empty.
Please see …

UN-3349 Neuro-SAN: Error raised when llm_config is omitted, despite being optional

---

neuro_san/session/async_http_service_agent_session.py

Let some specific asyncio-oriented asserts through so well-constructed clients can retry on them.
These cases were found by 1C stress tests.

UN-3355 Let through some specific asserts for AsyncHttpServiceAgentSession.streaming_chat()

---

neuro_san/test/unittest/unit_test_assert_forwarder.py

Better handle a problem that @vince-leaf uncovered

Assert that the container is not None before trying in/notIn tests

---

tests/neuro_san/internals/run_context/langchain/util/test_argument_validator.py

- Running tests with `pytest -m smoke` raised the following warning:
```
PytestCollectionWarning: cannot collect test class 'TestModel' because it has a init constructor
```
This was due to the helper Pydantic model named `TestModel`, which Pytest mistakenly treated as a test class during test discovery.
- Renamed `TestModel` to `SampleModel` to prevent Pytest from attempting to collect it as a test class. This eliminates the warning while preserving test functionality.
`test_argument_validator.py`

UN-3356 Neuro-san: [Smoketest] PytestCollectionWarning: cannot collect test class 'TestModel'

---

neuro_san/service/http/handlers/base_request_handler.py
neuro_san/service/http/server/http_server.py
neuro_san/service/http/server/http_server_app.py

This PR fixes a crash in neuro-san http server when we try to log an error in incoming request.
(Error code 404 for example).
Along the way, I added some extra logging logic for "standard" Tornado ErrorHandler to display client metadata together with other request parameters. Helpful for debugging the source of a problem.

UN-3360 Fix the HttpServer logger crash.

---

neuro_san/internals/run_context/langchain/core/langchain_run_context.py
neuro_san/internals/run_context/langchain/util/api_key_error_check.py

This PR is an attempt to neutralize a crash in LLM service stack I'm seeing when running my neuro-san stability tests,
which pretty repeatedly fail to finish now.
Essence of the problem:
a crash happens somewhere deep inside a stack and it is actually a RuntimeError ("bound to to different event loop" or something);
but while going up the call stack, it transforms into ConnectionError, which we treat specially:
we abort retry attempts and produce a helpful message to a client which in this case is very misleading.
So what I do: we try to examine not only the "final" exception, but the whole exception backtrace in search of keywords pointing to the real problem ("event loop" in our case). If these keywords are found, we fall back to general logic of running several retries.
Result: with …

UN-3357 Add separate check for internal errors in langchain stack.

---

neuro_san/test/driver/data_driven_agent_test_driver.py

This will help identify who is running tests against a server when that happens.
This helps shore up the cases coming from our software where user_id might not be set.

Put user_id in metadata from USER env var during tests by default

---

neuro_san/internals/run_context/langchain/llms/default_llm_factory.py

This PR improves error handling during LLM instantiation when factory-based resolution fails.
When all `llm_factories` fail to create an LLM, we fallback to using the `"class"` value in the config to attempt instantiation via a user-defined class. However, `"class"` is always set — even for factory-backed models like `"openai"` or `"bedrock"`.
If we blindly attempt to resolve these default classes again via `create_base_chat_model_from_user_class`, it can raise a secondary error that masks the original factory error, making debugging much harder.
Add a check to skip fallback resolution if `config["class"]` is one of the default classes.
This ensures we preserve and raise the original, meaningful exception instead of a misleading one from reprocessing default class paths.

Fix possible bug leading to wrong error message when instantiating LLM

---

neuro_san/deploy/Dockerfile
neuro_san/internals/chat/async_collating_queue.py
neuro_san/internals/chat/data_driven_chat_session.py
neuro_san/internals/journals/message_journal.py
neuro_san/internals/network_providers/agent_network_storage.py

I was looking to re-use AsyncCollatingQueue and I found something I thought to be suspicious:
an asynchronous call put() was putting something in the queue synchronously.
After some digging, I found this to be OK, but its usage needed to be made much more up-front than was currently done.
A couple other minor tweaks.
Tested: http chicken scenario. All agent_thinking comes over as expected.

UN-3352 Add synchronous flag to AsyncCollatingQueue.put() to be very clear as to what's going on

---

neuro_san/service/http/handlers/base_request_handler.py

This PR adds temporary debug logging for incoming requests with missing metadata.
We are hoping to find out where exactly a problem originates - on the client side
or maybe in the server internals.
Debug mode is controlled by SHOW_ABSENT_METADATA env variable which should be set to enable it.

UN-3377 Add debug check for missing request metadata.

---

neuro_san/internals/run_context/langchain/core/langchain_run_context.py
neuro_san/internals/run_context/langchain/journaling/journaling_callback_handler.py
neuro_san/internals/run_context/langchain/toolbox/toolbox_factory.py
tests/neuro_san/internals/run_context/langchain/toolbox/test_toolbox_factory.py

This PR introduces a proof of concept for logging (journaling) output from a LangChain tool using a callback-based approach.
For coded tools, journaling is handled within the activation class. However, LangChain tools are subclasses of LangChain’s `BaseTool`, and do not invoke our custom implementation (`LangchainOpenaiFunctionTool`) that creates an activation class and handles logging. As a result:
- No journal is created for LangChain tools.
- There is no clear indication when such a tool finishes execution.
Leverage `JournalingCallbackHandler`, which defines `on_tool_start()` and `on_tool_end()`—methods that are triggered at the start and end of tool execution.
Previously, callbacks were passed as arguments when instantiating the LLM, which limited their use to LLM-related events …

UN-3376 For langchain tools, make sure the UI knows that the communication between those nodes has been completed

---

neuro_san/internals/parsers/structure/json_structure_parser.py
tests/neuro_san/internals/parsers/structure/test_json_structure_parser.py

The expected output was:
{'running_cost': '0.00', 'origin': [{'tool': 'MusicNerdPro', 'instantiation_index': 1}, {'tool': 'Accountant', 'instantiation_index': 1}], 'origin_str': 'MusicNerdPro.Accountant'}
But the actual output was:
{'tool': 'Accountant', 'instantiation_index': 1}
This discrepancy occurs because the current logic in `JsonStructureParser` does not correctly handle nested dictionaries when extracting structured information.
Update the implementation of `JsonStructureParser.parse_structure()` to correctly handle and extract nested dictionary structures.
Manually ran `music_nerd_pro` and verified that the parsed structure now matches the expected format.

UN-3403 "structure_formats" makes output for thinking file of coded tool incomplete

---

.github/workflows/tests.yml

It's possible we can add this to other kinds of tests too (integration, smoke), but first things first.
We are at 50% overall coverage. Not bad given that there's a bunch of stuff that is very difficult to unit test.
Some specific areas have 100%, others have 0%.  The stuff that is 0% tends to be about server, interfaces, or CodedTool code that are not exercised during regular unit tests, but do have coverage in other ways, so 50% is actually a very low estimate.

Add unit test coverage stats when running regular unit tests

---

neuro_san/internals/graph/registry/agent_network.py

- Change logic of `AgentNetwork.find_front_man()` so that the first agent that is not coded tool or toolbox is the front man.
- Ran `music_nerd_pro_multi_agents` and confirmed correct front man selection.

UN-3406 Multiple frontman error when branch also has no parameters

---

neuro_san/internals/run_context/langchain/llms/default_llm_info.hocon
neuro_san/internals/run_context/langchain/llms/standard_langchain_llm_factory.py

The warning is from
https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/globals.py 
and can be trace back to https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/base.py#L92.
The fix is to set the value of `verbose` for chat models so it does not have to call the method to figure out the global default value.
Note that this warning only display for concurrent runs and is likely due to concurrent import of `langchain`.

UN-3441 UserWarning: Importing verbose from langchain root module is no longer supported langchain.globals.set_verbose()

---

neuro_san/service/main_loop/server_main_loop.py

In another branch when adding new args, pylint started complaining about parse_args() being to big. 
So this breaks it up.

Factor out arg prep in ServerMainLoop

---

.github/workflows/integration.yml
.github/workflows/publish.yml
.github/workflows/smoke.yml
.github/workflows/tests.yml

As per best practices, this PR explicitly sets github permissions in our action workflows. The workflows modified in this PR need only read access to the repo, so this is now spelled out explicitly.

Use minimal permissions in github action workflows

---

neuro_san/coded_tools/math_guy/async_closeable.py
neuro_san/coded_tools/math_guy/calculator.py
neuro_san/coded_tools/math_guy/sync_closeable.py
neuro_san/internals/chat/data_driven_chat_session.py

This will allow folks to share longer-lived objects amongst coded tools more properly.
Sharing could be amongst different coded tools, or different invocations of the same coded tool within the same agent network invocation.  This should also contribute to the resistance of anyone needing to use a global variable.

close() objects on sly_data that can be closed at the end of a session

---

neuro_san/registries/math_guy.hocon
tests/fixtures/math_guy/basic_sly_data.hocon
tests/fixtures/math_guy/forwarded_sly_data.hocon

Existing prompting on math_guy has started to fail intermittently in unit tests.
Most of the time the LLM was worried that it wasn't receiving any input and asking for it, when the input was actually coming from the sly_data.  This expectation of further input is what was making the unit tests fail because they only expected a single interaction.
This change makes the prompting less vague and asks the LLM to trust that the calculator tool will get its inputs by other means.  It's less anxious now and so far I haven't seen a failure.

Make math_guy unit test more reliable

---

tests/neuro_san/zzz_hocons/test_smoke_test_hocons.py

This PR is set to bypass the smoke test Ollama test case as it is becoming noisy for now [UN-3519]. We will reenable it after the issue has been addressed. I have added the comment to that ticket.

UN-3542 disable noisy ollama smoketest failure test case

---

neuro_san/internals/run_context/langchain/llms/default_llm_info.hocon

Per recent email from OpenAI some models are scheduled for shutdown:
Shutdown on March 26, 2026
* gpt-4-0314
* gpt-4-1106-preview
* gpt-4-0125-preview (including gpt-4-turbo-preview and gpt-4-turbo-preview-completions, which point to this snapshot)
Shutdown on September 28, 2026
* gpt-3.5-turbo-instruct
* babbage-002
* davinci-002
* gpt-3.5-turbo-1106
We refer to some of these, so adding a comment in the default_llm_info.hocon file about this.

Comment some models that are marked for shutdown by OpenAI
