neuro_san/client/direct_agent_session_factory.py

This PR puts back initialization for direct client session with everything
that is normally done on the server side.
If we are using neuro-san as a library, this needs to be done in client session.
Tested by running "web_search" and "music_nerd" agents as direct client session.

UN-3093 Properly initialize direct client session with everything a server would do.

---

MANIFEST.in
README.md
README_clients.md
pyproject.toml

Fix READMEs and other things for a cleaner wheel file.

Fix READMEs and other things for a cleaner wheel file

---

neuro_san/coded_tools/music_nerd_pro/accounting.py
neuro_san/registries/music_nerd_pro.hocon
tests/neuro_san/coded_tools/music_nerd_pro/test_accounting.py

This PR aims to address the 10% to 20% false failure rate. The additional instructions I added allow me to avoid false failures.

UN-3122 Fixed music nerd pro random false failure

---

.github/workflows/tests.yml

This PR should take care of the duplicate test runs that occurred at a PR.

Modify trigger to avoid duplicate test run at PRs

---

docs/agent_hocon_reference.md

- Add agent_lllm_info_file section

Add "agent_lllm_info_file" section in agent_hocon_reference.md

---

docs/agent_hocon_reference.md
docs/llm_info_hocon_reference.md
neuro_san/internals/run_context/langchain/default_llm_info.hocon

* Add content to llm_info_hocon_reference.md
* Better cross referencing in agent_hocon_reference.md and shipping default_llm_info.hocon file.

llm_info hocon reference docs

---

.github/workflows/smoke.yml

This PR addresses the inability to check that the server service has started.

UN-3143 tweaked to get server service start

---

neuro_san/registries/music_nerd_pro.hocon
neuro_san/registries/music_nerd_pro_llm_anthropic.hocon

Adopt the prompting changes from neuro-san-studio's music_nerd_pro for more reliable JSON output across different LLMs.

Update music_nerd_pro instructions for more reliable JSON output

---

tests/fixtures/music_nerd_pro/combination_responses_with_history_direct.hocon
tests/fixtures/music_nerd_pro/combination_responses_with_history_grpc.hocon
tests/fixtures/music_nerd_pro/combination_responses_with_history_http.hocon
tests/fixtures/music_nerd_pro_llm_anthropic/combination_responses_with_history_direct.hocon
tests/neuro_san/hocon_tests/smoke/music_nerd_pro/test_smoke_test_hocons.py
tests/neuro_san/hocon_tests/smoke/music_nerd_pro/test_smoke_test_hocons_llm_anthropic.py

This PR will address two issues:
1. Added timeout to deal with test case using agent_cli run to infinity 
2. The AI final answer on Music_nerd_pro is all in the string, unlike before combining string and JSON.

UN-3220 UN-3222:  Add timeout & Fixed broken smoke test cases

---

docs/agent_hocon_reference.md

And, fixed a bunch of lint issues

Removed the verbose section from documantation. 

---

README.md

- Put deepwiki badge and link in the README.md for auto-refresh.

UN-3288 Add link to DeepWiki in top-level neuro-san README. Tag to update DeepWiki 1/week

---

neuro_san/http_sidecar/handlers/health_check_handler.py
neuro_san/http_sidecar/http_sidecar.py

Simple PR to add standard /healthz health check endpoint to http service.

UN-3152 Add /healthz endpoint for health check.

---

neuro_san/service/http/handlers/base_request_handler.py
neuro_san/service/http/handlers/concierge_handler.py
neuro_san/service/http/handlers/connectivity_handler.py
neuro_san/service/http/server/http_sidecar.py
neuro_san/service/main_loop/server_main_loop.py

Title says it all. Tested beatles scenario.
This came about when poking around how the AgentNetwork storage system worked.
I _think_ I can do all this ...

Remove lingering gRPC-isms from HTTP server

---

neuro_san/internals/run_context/langchain/llms/default_llm_info.hocon

Add `claude-sonnet-4-0` and `claude-opus-4-0` models to `default_llm_info.hocon`.

Add claude 4.0

---

neuro_san/internals/run_context/langchain/llms/default_llm_info.hocon

This should be the model for testing.

Add qwen3 model for Ollama

---

neuro_san/service/usage/wrapped_usage_logger.py

Fix syntax error in WrappedUsageLogger.

---

neuro_san/client/agent_cli.py
neuro_san/client/streaming_input_processor.py
neuro_san/internals/filters/token_accounting_message_filter.py
neuro_san/message_processing/basic_message_processor.py
neuro_san/message_processing/token_accounting_message_processor.py

UN-3366 Add token accounting output to agent_cli via StreamingInputProcessor

---

neuro_san/internals/graph/registry/agent_network.py
neuro_san/registries/assess_failure.hocon
neuro_san/registries/bing_search.hocon
neuro_san/registries/date_time.hocon
neuro_san/registries/esp_decision_assistant.hocon
neuro_san/registries/gist.hocon
neuro_san/registries/google_serper.hocon
neuro_san/registries/hello_world.hocon
neuro_san/registries/intranet_agents.hocon
neuro_san/registries/math_guy.hocon
neuro_san/registries/math_guy_passthrough.hocon
neuro_san/registries/music_nerd.hocon
neuro_san/registries/music_nerd_pro.hocon
neuro_san/registries/music_nerd_pro_llm_anthropic.hocon
neuro_san/registries/music_nerd_pro_llm_azure.hocon
neuro_san/registries/music_nerd_pro_llm_bedrock_claude.hocon
neuro_san/registries/music_nerd_pro_llm_gemini.hocon
neuro_san/registries/music_nerd_pro_llm_ollama.hocon
neuro_san/registries/music_nerd_pro_multi_agents.hocon
neuro_san/registries/website_rag.hocon
neuro_san/registries/website_search.hocon
neuro_san/registries/website_search_usage_example.hocon

Updated the hocon file documentation accordingly

Changed the logic for frontman, so it is always the first agent.

---

neuro_san/internals/graph/activations/branch_activation.py
neuro_san/internals/graph/activations/external_activation.py

* Restore some help in BranchActivation that pertains to external tools.
* Fix a return case in ExternalActivations that I missed earlier.

Fix some return value in BranchActivation. Restore help in ExternalActivation

---

docs/clients.md

UN-3494 Add docs for curl and sly_data in clients.md docs

---

tests/fixtures/esp_decision_assistant/fallbacks_and_commondef_values.hocon
tests/fixtures/hello_world/hello_world.hocon
tests/fixtures/mcp_deepwiki_dict/cail_neuro_san.hocon
tests/neuro_san/zzz_hocons/test_integration_test_hocons.py
tests/neuro_san/zzz_hocons/test_unit_test_hocons.py

* Move mcp test to integration tests
* Change timeout on another integration test so it passes more frequently as well
* Fix a comment.

Move mcp test to integration tests. Fix other test case hocons.
